name: Deploy to Firebase App Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Deploy to App Hosting
        uses: 'firebase/firebase-actions/setup-app-hosting@v0'
        with:
          app_id: '1:1091566374921:web:29b563603d6d541573c73c'
          api_key: '${{ secrets.FIREBASE_API_KEY }}'
